// <auto-generated />
namespace Reminder_desktop_application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addTableUserModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableUserModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201806291758397_addTableUserModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
